apiVersion: v1
kind: Pod
metadata:
  name: db-test-pod
  namespace: db
spec:
  containers:
  - name: busybox
    image: busybox:1.31.0-uclibc
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    stdin: true
    tty: true